package com.example.sample.domain.model.maintenance;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

/**
 * クラスの説明：
 * @author kamagata
 * @since 2018/02/11
 */
@Component
@Scope("prototype")
public class GenreLgExample {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table GENRE_LG
	 * @mbg.generated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table GENRE_LG
	 * @mbg.generated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table GENRE_LG
	 * @mbg.generated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_LG
	 * @mbg.generated
	 */
	public GenreLgExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_LG
	 * @mbg.generated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_LG
	 * @mbg.generated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_LG
	 * @mbg.generated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_LG
	 * @mbg.generated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_LG
	 * @mbg.generated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_LG
	 * @mbg.generated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_LG
	 * @mbg.generated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_LG
	 * @mbg.generated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_LG
	 * @mbg.generated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_LG
	 * @mbg.generated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table GENRE_LG
	 * @mbg.generated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andGenreLgCdIsNull() {
			addCriterion("GENRE_LG_CD is null");
			return (Criteria) this;
		}

		public Criteria andGenreLgCdIsNotNull() {
			addCriterion("GENRE_LG_CD is not null");
			return (Criteria) this;
		}

		public Criteria andGenreLgCdEqualTo(String value) {
			addCriterion("GENRE_LG_CD =", value, "genreLgCd");
			return (Criteria) this;
		}

		public Criteria andGenreLgCdNotEqualTo(String value) {
			addCriterion("GENRE_LG_CD <>", value, "genreLgCd");
			return (Criteria) this;
		}

		public Criteria andGenreLgCdGreaterThan(String value) {
			addCriterion("GENRE_LG_CD >", value, "genreLgCd");
			return (Criteria) this;
		}

		public Criteria andGenreLgCdGreaterThanOrEqualTo(String value) {
			addCriterion("GENRE_LG_CD >=", value, "genreLgCd");
			return (Criteria) this;
		}

		public Criteria andGenreLgCdLessThan(String value) {
			addCriterion("GENRE_LG_CD <", value, "genreLgCd");
			return (Criteria) this;
		}

		public Criteria andGenreLgCdLessThanOrEqualTo(String value) {
			addCriterion("GENRE_LG_CD <=", value, "genreLgCd");
			return (Criteria) this;
		}

		public Criteria andGenreLgCdLike(String value) {
			addCriterion("GENRE_LG_CD like", value, "genreLgCd");
			return (Criteria) this;
		}

		public Criteria andGenreLgCdNotLike(String value) {
			addCriterion("GENRE_LG_CD not like", value, "genreLgCd");
			return (Criteria) this;
		}

		public Criteria andGenreLgCdIn(List<String> values) {
			addCriterion("GENRE_LG_CD in", values, "genreLgCd");
			return (Criteria) this;
		}

		public Criteria andGenreLgCdNotIn(List<String> values) {
			addCriterion("GENRE_LG_CD not in", values, "genreLgCd");
			return (Criteria) this;
		}

		public Criteria andGenreLgCdBetween(String value1, String value2) {
			addCriterion("GENRE_LG_CD between", value1, value2, "genreLgCd");
			return (Criteria) this;
		}

		public Criteria andGenreLgCdNotBetween(String value1, String value2) {
			addCriterion("GENRE_LG_CD not between", value1, value2, "genreLgCd");
			return (Criteria) this;
		}

		public Criteria andGenreLgNmIsNull() {
			addCriterion("GENRE_LG_NM is null");
			return (Criteria) this;
		}

		public Criteria andGenreLgNmIsNotNull() {
			addCriterion("GENRE_LG_NM is not null");
			return (Criteria) this;
		}

		public Criteria andGenreLgNmEqualTo(String value) {
			addCriterion("GENRE_LG_NM =", value, "genreLgNm");
			return (Criteria) this;
		}

		public Criteria andGenreLgNmNotEqualTo(String value) {
			addCriterion("GENRE_LG_NM <>", value, "genreLgNm");
			return (Criteria) this;
		}

		public Criteria andGenreLgNmGreaterThan(String value) {
			addCriterion("GENRE_LG_NM >", value, "genreLgNm");
			return (Criteria) this;
		}

		public Criteria andGenreLgNmGreaterThanOrEqualTo(String value) {
			addCriterion("GENRE_LG_NM >=", value, "genreLgNm");
			return (Criteria) this;
		}

		public Criteria andGenreLgNmLessThan(String value) {
			addCriterion("GENRE_LG_NM <", value, "genreLgNm");
			return (Criteria) this;
		}

		public Criteria andGenreLgNmLessThanOrEqualTo(String value) {
			addCriterion("GENRE_LG_NM <=", value, "genreLgNm");
			return (Criteria) this;
		}

		public Criteria andGenreLgNmLike(String value) {
			addCriterion("GENRE_LG_NM like", value, "genreLgNm");
			return (Criteria) this;
		}

		public Criteria andGenreLgNmNotLike(String value) {
			addCriterion("GENRE_LG_NM not like", value, "genreLgNm");
			return (Criteria) this;
		}

		public Criteria andGenreLgNmIn(List<String> values) {
			addCriterion("GENRE_LG_NM in", values, "genreLgNm");
			return (Criteria) this;
		}

		public Criteria andGenreLgNmNotIn(List<String> values) {
			addCriterion("GENRE_LG_NM not in", values, "genreLgNm");
			return (Criteria) this;
		}

		public Criteria andGenreLgNmBetween(String value1, String value2) {
			addCriterion("GENRE_LG_NM between", value1, value2, "genreLgNm");
			return (Criteria) this;
		}

		public Criteria andGenreLgNmNotBetween(String value1, String value2) {
			addCriterion("GENRE_LG_NM not between", value1, value2, "genreLgNm");
			return (Criteria) this;
		}

		public Criteria andDisplayOrderIsNull() {
			addCriterion("DISPLAY_ORDER is null");
			return (Criteria) this;
		}

		public Criteria andDisplayOrderIsNotNull() {
			addCriterion("DISPLAY_ORDER is not null");
			return (Criteria) this;
		}

		public Criteria andDisplayOrderEqualTo(Short value) {
			addCriterion("DISPLAY_ORDER =", value, "displayOrder");
			return (Criteria) this;
		}

		public Criteria andDisplayOrderNotEqualTo(Short value) {
			addCriterion("DISPLAY_ORDER <>", value, "displayOrder");
			return (Criteria) this;
		}

		public Criteria andDisplayOrderGreaterThan(Short value) {
			addCriterion("DISPLAY_ORDER >", value, "displayOrder");
			return (Criteria) this;
		}

		public Criteria andDisplayOrderGreaterThanOrEqualTo(Short value) {
			addCriterion("DISPLAY_ORDER >=", value, "displayOrder");
			return (Criteria) this;
		}

		public Criteria andDisplayOrderLessThan(Short value) {
			addCriterion("DISPLAY_ORDER <", value, "displayOrder");
			return (Criteria) this;
		}

		public Criteria andDisplayOrderLessThanOrEqualTo(Short value) {
			addCriterion("DISPLAY_ORDER <=", value, "displayOrder");
			return (Criteria) this;
		}

		public Criteria andDisplayOrderIn(List<Short> values) {
			addCriterion("DISPLAY_ORDER in", values, "displayOrder");
			return (Criteria) this;
		}

		public Criteria andDisplayOrderNotIn(List<Short> values) {
			addCriterion("DISPLAY_ORDER not in", values, "displayOrder");
			return (Criteria) this;
		}

		public Criteria andDisplayOrderBetween(Short value1, Short value2) {
			addCriterion("DISPLAY_ORDER between", value1, value2, "displayOrder");
			return (Criteria) this;
		}

		public Criteria andDisplayOrderNotBetween(Short value1, Short value2) {
			addCriterion("DISPLAY_ORDER not between", value1, value2, "displayOrder");
			return (Criteria) this;
		}

		public Criteria andBikoIsNull() {
			addCriterion("BIKO is null");
			return (Criteria) this;
		}

		public Criteria andBikoIsNotNull() {
			addCriterion("BIKO is not null");
			return (Criteria) this;
		}

		public Criteria andBikoEqualTo(String value) {
			addCriterion("BIKO =", value, "biko");
			return (Criteria) this;
		}

		public Criteria andBikoNotEqualTo(String value) {
			addCriterion("BIKO <>", value, "biko");
			return (Criteria) this;
		}

		public Criteria andBikoGreaterThan(String value) {
			addCriterion("BIKO >", value, "biko");
			return (Criteria) this;
		}

		public Criteria andBikoGreaterThanOrEqualTo(String value) {
			addCriterion("BIKO >=", value, "biko");
			return (Criteria) this;
		}

		public Criteria andBikoLessThan(String value) {
			addCriterion("BIKO <", value, "biko");
			return (Criteria) this;
		}

		public Criteria andBikoLessThanOrEqualTo(String value) {
			addCriterion("BIKO <=", value, "biko");
			return (Criteria) this;
		}

		public Criteria andBikoLike(String value) {
			addCriterion("BIKO like", value, "biko");
			return (Criteria) this;
		}

		public Criteria andBikoNotLike(String value) {
			addCriterion("BIKO not like", value, "biko");
			return (Criteria) this;
		}

		public Criteria andBikoIn(List<String> values) {
			addCriterion("BIKO in", values, "biko");
			return (Criteria) this;
		}

		public Criteria andBikoNotIn(List<String> values) {
			addCriterion("BIKO not in", values, "biko");
			return (Criteria) this;
		}

		public Criteria andBikoBetween(String value1, String value2) {
			addCriterion("BIKO between", value1, value2, "biko");
			return (Criteria) this;
		}

		public Criteria andBikoNotBetween(String value1, String value2) {
			addCriterion("BIKO not between", value1, value2, "biko");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgIsNull() {
			addCriterion("DELETE_FLG is null");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgIsNotNull() {
			addCriterion("DELETE_FLG is not null");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgEqualTo(String value) {
			addCriterion("DELETE_FLG =", value, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgNotEqualTo(String value) {
			addCriterion("DELETE_FLG <>", value, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgGreaterThan(String value) {
			addCriterion("DELETE_FLG >", value, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgGreaterThanOrEqualTo(String value) {
			addCriterion("DELETE_FLG >=", value, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgLessThan(String value) {
			addCriterion("DELETE_FLG <", value, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgLessThanOrEqualTo(String value) {
			addCriterion("DELETE_FLG <=", value, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgLike(String value) {
			addCriterion("DELETE_FLG like", value, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgNotLike(String value) {
			addCriterion("DELETE_FLG not like", value, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgIn(List<String> values) {
			addCriterion("DELETE_FLG in", values, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgNotIn(List<String> values) {
			addCriterion("DELETE_FLG not in", values, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgBetween(String value1, String value2) {
			addCriterion("DELETE_FLG between", value1, value2, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgNotBetween(String value1, String value2) {
			addCriterion("DELETE_FLG not between", value1, value2, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andInsertDtIsNull() {
			addCriterion("INSERT_DT is null");
			return (Criteria) this;
		}

		public Criteria andInsertDtIsNotNull() {
			addCriterion("INSERT_DT is not null");
			return (Criteria) this;
		}

		public Criteria andInsertDtEqualTo(Date value) {
			addCriterion("INSERT_DT =", value, "insertDt");
			return (Criteria) this;
		}

		public Criteria andInsertDtNotEqualTo(Date value) {
			addCriterion("INSERT_DT <>", value, "insertDt");
			return (Criteria) this;
		}

		public Criteria andInsertDtGreaterThan(Date value) {
			addCriterion("INSERT_DT >", value, "insertDt");
			return (Criteria) this;
		}

		public Criteria andInsertDtGreaterThanOrEqualTo(Date value) {
			addCriterion("INSERT_DT >=", value, "insertDt");
			return (Criteria) this;
		}

		public Criteria andInsertDtLessThan(Date value) {
			addCriterion("INSERT_DT <", value, "insertDt");
			return (Criteria) this;
		}

		public Criteria andInsertDtLessThanOrEqualTo(Date value) {
			addCriterion("INSERT_DT <=", value, "insertDt");
			return (Criteria) this;
		}

		public Criteria andInsertDtIn(List<Date> values) {
			addCriterion("INSERT_DT in", values, "insertDt");
			return (Criteria) this;
		}

		public Criteria andInsertDtNotIn(List<Date> values) {
			addCriterion("INSERT_DT not in", values, "insertDt");
			return (Criteria) this;
		}

		public Criteria andInsertDtBetween(Date value1, Date value2) {
			addCriterion("INSERT_DT between", value1, value2, "insertDt");
			return (Criteria) this;
		}

		public Criteria andInsertDtNotBetween(Date value1, Date value2) {
			addCriterion("INSERT_DT not between", value1, value2, "insertDt");
			return (Criteria) this;
		}

		public Criteria andInsertCdIsNull() {
			addCriterion("INSERT_CD is null");
			return (Criteria) this;
		}

		public Criteria andInsertCdIsNotNull() {
			addCriterion("INSERT_CD is not null");
			return (Criteria) this;
		}

		public Criteria andInsertCdEqualTo(Long value) {
			addCriterion("INSERT_CD =", value, "insertCd");
			return (Criteria) this;
		}

		public Criteria andInsertCdNotEqualTo(Long value) {
			addCriterion("INSERT_CD <>", value, "insertCd");
			return (Criteria) this;
		}

		public Criteria andInsertCdGreaterThan(Long value) {
			addCriterion("INSERT_CD >", value, "insertCd");
			return (Criteria) this;
		}

		public Criteria andInsertCdGreaterThanOrEqualTo(Long value) {
			addCriterion("INSERT_CD >=", value, "insertCd");
			return (Criteria) this;
		}

		public Criteria andInsertCdLessThan(Long value) {
			addCriterion("INSERT_CD <", value, "insertCd");
			return (Criteria) this;
		}

		public Criteria andInsertCdLessThanOrEqualTo(Long value) {
			addCriterion("INSERT_CD <=", value, "insertCd");
			return (Criteria) this;
		}

		public Criteria andInsertCdIn(List<Long> values) {
			addCriterion("INSERT_CD in", values, "insertCd");
			return (Criteria) this;
		}

		public Criteria andInsertCdNotIn(List<Long> values) {
			addCriterion("INSERT_CD not in", values, "insertCd");
			return (Criteria) this;
		}

		public Criteria andInsertCdBetween(Long value1, Long value2) {
			addCriterion("INSERT_CD between", value1, value2, "insertCd");
			return (Criteria) this;
		}

		public Criteria andInsertCdNotBetween(Long value1, Long value2) {
			addCriterion("INSERT_CD not between", value1, value2, "insertCd");
			return (Criteria) this;
		}

		public Criteria andUpdateDtIsNull() {
			addCriterion("UPDATE_DT is null");
			return (Criteria) this;
		}

		public Criteria andUpdateDtIsNotNull() {
			addCriterion("UPDATE_DT is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateDtEqualTo(Date value) {
			addCriterion("UPDATE_DT =", value, "updateDt");
			return (Criteria) this;
		}

		public Criteria andUpdateDtNotEqualTo(Date value) {
			addCriterion("UPDATE_DT <>", value, "updateDt");
			return (Criteria) this;
		}

		public Criteria andUpdateDtGreaterThan(Date value) {
			addCriterion("UPDATE_DT >", value, "updateDt");
			return (Criteria) this;
		}

		public Criteria andUpdateDtGreaterThanOrEqualTo(Date value) {
			addCriterion("UPDATE_DT >=", value, "updateDt");
			return (Criteria) this;
		}

		public Criteria andUpdateDtLessThan(Date value) {
			addCriterion("UPDATE_DT <", value, "updateDt");
			return (Criteria) this;
		}

		public Criteria andUpdateDtLessThanOrEqualTo(Date value) {
			addCriterion("UPDATE_DT <=", value, "updateDt");
			return (Criteria) this;
		}

		public Criteria andUpdateDtIn(List<Date> values) {
			addCriterion("UPDATE_DT in", values, "updateDt");
			return (Criteria) this;
		}

		public Criteria andUpdateDtNotIn(List<Date> values) {
			addCriterion("UPDATE_DT not in", values, "updateDt");
			return (Criteria) this;
		}

		public Criteria andUpdateDtBetween(Date value1, Date value2) {
			addCriterion("UPDATE_DT between", value1, value2, "updateDt");
			return (Criteria) this;
		}

		public Criteria andUpdateDtNotBetween(Date value1, Date value2) {
			addCriterion("UPDATE_DT not between", value1, value2, "updateDt");
			return (Criteria) this;
		}

		public Criteria andUpdateCdIsNull() {
			addCriterion("UPDATE_CD is null");
			return (Criteria) this;
		}

		public Criteria andUpdateCdIsNotNull() {
			addCriterion("UPDATE_CD is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateCdEqualTo(Long value) {
			addCriterion("UPDATE_CD =", value, "updateCd");
			return (Criteria) this;
		}

		public Criteria andUpdateCdNotEqualTo(Long value) {
			addCriterion("UPDATE_CD <>", value, "updateCd");
			return (Criteria) this;
		}

		public Criteria andUpdateCdGreaterThan(Long value) {
			addCriterion("UPDATE_CD >", value, "updateCd");
			return (Criteria) this;
		}

		public Criteria andUpdateCdGreaterThanOrEqualTo(Long value) {
			addCriterion("UPDATE_CD >=", value, "updateCd");
			return (Criteria) this;
		}

		public Criteria andUpdateCdLessThan(Long value) {
			addCriterion("UPDATE_CD <", value, "updateCd");
			return (Criteria) this;
		}

		public Criteria andUpdateCdLessThanOrEqualTo(Long value) {
			addCriterion("UPDATE_CD <=", value, "updateCd");
			return (Criteria) this;
		}

		public Criteria andUpdateCdIn(List<Long> values) {
			addCriterion("UPDATE_CD in", values, "updateCd");
			return (Criteria) this;
		}

		public Criteria andUpdateCdNotIn(List<Long> values) {
			addCriterion("UPDATE_CD not in", values, "updateCd");
			return (Criteria) this;
		}

		public Criteria andUpdateCdBetween(Long value1, Long value2) {
			addCriterion("UPDATE_CD between", value1, value2, "updateCd");
			return (Criteria) this;
		}

		public Criteria andUpdateCdNotBetween(Long value1, Long value2) {
			addCriterion("UPDATE_CD not between", value1, value2, "updateCd");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table GENRE_LG
	 * @mbg.generated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
	 * This class was generated by MyBatis Generator.
	 * This class corresponds to the database table GENRE_LG
	 *
	 * @mbg.generated do_not_delete_during_merge
	 */
	public static class Criteria extends GeneratedCriteria {

		protected Criteria() {
			super();
		}
	}
}