package com.example.sample.domain.model.maintenance;

import java.io.Serializable;
import java.util.Date;

import lombok.Data;
import lombok.NoArgsConstructor;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table GENRE_MD
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Data
@NoArgsConstructor
public class GenreMd implements Serializable {
	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column GENRE_MD.GENRE_MD_CD
	 *
	 * @mbg.generated
	 */
	private String genreMdCd;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column GENRE_MD.GENRE_MD_NM
	 *
	 * @mbg.generated
	 */
	private String genreMdNm;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column GENRE_MD.DISPLAY_ORDER
	 *
	 * @mbg.generated
	 */
	private Short displayOrder;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column GENRE_MD.GENRE_LG_CD
	 *
	 * @mbg.generated
	 */
	private String genreLgCd;

	private GenreLg genreLg;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column GENRE_MD.BIKO
	 *
	 * @mbg.generated
	 */
	private String biko;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column GENRE_MD.DELETE_FLG
	 *
	 * @mbg.generated
	 */
	private String deleteFlg;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column GENRE_MD.INSERT_CD
	 *
	 * @mbg.generated
	 */
	private Long insertCd;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column GENRE_MD.INSERT_DT
	 *
	 * @mbg.generated
	 */
	private Date insertDt;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column GENRE_MD.UPDATE_CD
	 *
	 * @mbg.generated
	 */
	private Long updateCd;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column GENRE_MD.UPDATE_DT
	 *
	 * @mbg.generated
	 */
	private Date updateDt;
}