package com.example.sample.domain.model.maintenance;

import java.io.Serializable;
import java.util.Date;

import lombok.Data;
import lombok.NoArgsConstructor;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table GENRE_LG
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Data
@NoArgsConstructor
public class GenreLg implements Serializable {
	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column GENRE_LG.GENRE_LG_CD
	 *
	 * @mbg.generated
	 */
	private String genreLgCd;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column GENRE_LG.GENRE_LG_NM
	 *
	 * @mbg.generated
	 */
	private String genreLgNm;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column GENRE_LG.DISPLAY_ORDER
	 *
	 * @mbg.generated
	 */
	private Short displayOrder;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column GENRE_LG.BIKO
	 *
	 * @mbg.generated
	 */
	private String biko;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column GENRE_LG.DELETE_FLG
	 *
	 * @mbg.generated
	 */
	private String deleteFlg;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column GENRE_LG.INSERT_DT
	 *
	 * @mbg.generated
	 */
	private Date insertDt;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column GENRE_LG.INSERT_CD
	 *
	 * @mbg.generated
	 */
	private Long insertCd;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column GENRE_LG.UPDATE_DT
	 *
	 * @mbg.generated
	 */
	private Date updateDt;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column GENRE_LG.UPDATE_CD
	 *
	 * @mbg.generated
	 */
	private Long updateCd;
}