package com.example.sample.domain.entity.common;

import java.io.Serializable;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table USER_INFO
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = false)
public class UserInfoEntity extends CommonColumnEntity implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USER_INFO.USER_CD
	 * @mbg.generated
	 */
	private Long userCd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USER_INFO.FIRST_NM
	 * @mbg.generated
	 */
	private String firstNm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USER_INFO.LAST_NM
	 * @mbg.generated
	 */
	private String lastNm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USER_INFO.EMAIL
	 * @mbg.generated
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USER_INFO.PHONE
	 * @mbg.generated
	 */
	private Long phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USER_INFO.PASSWORD
	 * @mbg.generated
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USER_INFO.AUTH
	 * @mbg.generated
	 */
	private String auth;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table USER_INFO
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * メソッドの説明：管理者権限有無
	 * @author kamagata
	 * @since 2018/02/25
	 * @return True:管理者、False:一般
	 */
	public boolean isAdmin() {
		return auth.equals("2");
	}
}