package com.example.sample.domain.mapper.maintenance;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.example.sample.domain.entity.maintenance.GenreMdCriteria;
import com.example.sample.domain.entity.maintenance.GenreMdEntity;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

@Mapper
public interface GenreMdMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_MD
	 * @mbg.generated
	 */
	long countByCriteria(GenreMdCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_MD
	 * @mbg.generated
	 */
	int deleteByCriteria(GenreMdCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_MD
	 * @mbg.generated
	 */
	@Delete({ "delete from GENRE_MD", "where GENRE_MD_CD = #{genreMdCd,jdbcType=CHAR}" })
	int deleteByPrimaryKey(String genreMdCd);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_MD
	 * @mbg.generated
	 */
	@Insert({ "insert into GENRE_MD (GENRE_MD_CD, GENRE_MD_NM, ", "DISPLAY_ORDER, GENRE_LG_CD, ", "BIKO, DELETE_FLG, ",
			"INSERT_CD, INSERT_DT, ", "UPDATE_CD, UPDATE_DT)",
			"values (#{genreMdCd,jdbcType=CHAR}, #{genreMdNm,jdbcType=VARCHAR}, ",
			"#{displayOrder,jdbcType=DECIMAL}, #{genreLgCd,jdbcType=CHAR}, ",
			"#{biko,jdbcType=VARCHAR}, #{deleteFlg,jdbcType=VARCHAR}, ",
			"#{insertCd,jdbcType=DECIMAL}, #{insertDt,jdbcType=TIMESTAMP}, ",
			"#{updateCd,jdbcType=DECIMAL}, #{updateDt,jdbcType=TIMESTAMP})" })
	int insert(GenreMdEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_MD
	 * @mbg.generated
	 */
	int insertSelective(GenreMdEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_MD
	 * @mbg.generated
	 */
	List<GenreMdEntity> selectByCriteriaWithRowbounds(GenreMdCriteria example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_MD
	 * @mbg.generated
	 */
	List<GenreMdEntity> selectByCriteria(GenreMdCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_MD
	 * @mbg.generated
	 */
	@Select({ "select",
			"MD.GENRE_MD_CD as MD_GENRE_MD_CD, MD.GENRE_MD_NM as MD_GENRE_MD_NM, MD.DISPLAY_ORDER as MD_DISPLAY_ORDER, ",
			"MD.GENRE_LG_CD as MD_GENRE_LG_CD, MD.BIKO as MD_BIKO, MD.DELETE_FLG as MD_DELETE_FLG, ",
			"MD.INSERT_CD as MD_INSERT_CD, MD.INSERT_DT as MD_INSERT_DT, MD.UPDATE_CD as MD_UPDATE_CD, ",
			"MD.UPDATE_DT as MD_UPDATE_DT", "from GENRE_MD MD", "where MD.GENRE_MD_CD = #{genreMdCd,jdbcType=CHAR}" })
	@ResultMap("com.example.sample.domain.mapper.maintenance.GenreMdMapper.BaseResultMap")
	GenreMdEntity selectByPrimaryKey(String genreMdCd);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_MD
	 * @mbg.generated
	 */
	int updateByCriteriaSelective(@Param("record") GenreMdEntity record, @Param("example") GenreMdCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_MD
	 * @mbg.generated
	 */
	int updateByCriteria(@Param("record") GenreMdEntity record, @Param("example") GenreMdCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_MD
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(GenreMdEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_MD
	 * @mbg.generated
	 */
	@Update({ "update GENRE_MD", "set GENRE_MD_NM = #{genreMdNm,jdbcType=VARCHAR},",
			"DISPLAY_ORDER = #{displayOrder,jdbcType=DECIMAL},", "GENRE_LG_CD = #{genreLgCd,jdbcType=CHAR},",
			"BIKO = #{biko,jdbcType=VARCHAR},", "DELETE_FLG = #{deleteFlg,jdbcType=VARCHAR},",
			"INSERT_CD = #{insertCd,jdbcType=DECIMAL},", "INSERT_DT = #{insertDt,jdbcType=TIMESTAMP},",
			"UPDATE_CD = #{updateCd,jdbcType=DECIMAL},", "UPDATE_DT = #{updateDt,jdbcType=TIMESTAMP}",
			"where GENRE_MD_CD = #{genreMdCd,jdbcType=CHAR}" })
	int updateByPrimaryKey(GenreMdEntity record);

	/**
	 * メソッドの説明：大ジャンルを含めた検索
	 * @author kamagata
	 * @since 2018/02/15
	 * @param criteria 検索条件
	 * @return List<GenreMd> 大ジャンルエンティティのリスト
	 */
	List<GenreMdEntity> selectGenreLgAndMdByCriteria(GenreMdCriteria criteria);
}