package com.example.sample.domain.mapper.maintenance;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.example.sample.domain.model.maintenance.GenreLg;
import com.example.sample.domain.model.maintenance.GenreLgExample;

/**
 * クラスの説明：大ジャンルマスタ　Mapper
 * @author kamagata
 * @since 2018/02/11
 */
@Mapper
@Repository
public interface GenreLgMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_LG
	 * @mbg.generated
	 */
	long countByExample(GenreLgExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_LG
	 * @mbg.generated
	 */
	int deleteByExample(GenreLgExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_LG
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String genreLgCd);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_LG
	 * @mbg.generated
	 */
	int insert(GenreLg record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_LG
	 * @mbg.generated
	 */
	int insertSelective(GenreLg record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_LG
	 * @mbg.generated
	 */
	List<GenreLg> selectByExample(GenreLgExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_LG
	 * @mbg.generated
	 */
	GenreLg selectByPrimaryKey(String genreLgCd);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_LG
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") GenreLg record, @Param("example") GenreLgExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_LG
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") GenreLg record, @Param("example") GenreLgExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_LG
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(GenreLg record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_LG
	 * @mbg.generated
	 */
	int updateByPrimaryKey(GenreLg record);
}