package com.example.sample.domain.mapper.maintenance;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.example.sample.domain.entity.maintenance.GenreMdCriteria;
import com.example.sample.domain.entity.maintenance.GenreMdEntity;

@Mapper
public interface GenreMdMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_MD
	 * @mbg.generated
	 */
	long countByExample(GenreMdCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_MD
	 * @mbg.generated
	 */
	int deleteByExample(GenreMdCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_MD
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String genreMdCd);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_MD
	 * @mbg.generated
	 */
	int insert(GenreMdEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_MD
	 * @mbg.generated
	 */
	int insertSelective(GenreMdEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_MD
	 * @mbg.generated
	 */
	List<GenreMdEntity> selectByExampleWithRowbounds(GenreMdCriteria example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_MD
	 * @mbg.generated
	 */
	List<GenreMdEntity> selectByExample(GenreMdCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_MD
	 * @mbg.generated
	 */
	GenreMdEntity selectByPrimaryKey(String genreMdCd);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_MD
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") GenreMdEntity record, @Param("example") GenreMdCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_MD
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") GenreMdEntity record, @Param("example") GenreMdCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_MD
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(GenreMdEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_MD
	 * @mbg.generated
	 */
	int updateByPrimaryKey(GenreMdEntity record);

	/**
	 * メソッドの説明：大ジャンルを含めた検索
	 * @author kamagata
	 * @since 2018/02/15
	 * @param criteria 検索条件
	 * @return List<GenreMd> 大ジャンルエンティティのリスト
	 */
	List<GenreMdEntity> selectGenreLgAndMdByCriteria(GenreMdCriteria criteria);
}