package com.example.sample.domain.mapper.maintenance;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

import com.example.sample.domain.entity.maintenance.GenreLgCriteria;
import com.example.sample.domain.entity.maintenance.GenreLgEntity;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

/**
 * クラスの説明：大ジャンルマスタ　Mapper
 * @author kamagata
 * @since 2018/02/11
 */
@Mapper
@Repository
public interface GenreLgMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_LG
	 * @mbg.generated
	 */
	long countByExample(GenreLgCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_LG
	 * @mbg.generated
	 */
	int deleteByExample(GenreLgCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_LG
	 * @mbg.generated
	 */
	@Delete({ "delete from GENRE_LG", "where GENRE_LG_CD = #{genreLgCd,jdbcType=CHAR}" })
	int deleteByPrimaryKey(String genreLgCd);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_LG
	 * @mbg.generated
	 */
	@Insert({ "insert into GENRE_LG (GENRE_LG_CD, GENRE_LG_NM, ", "DISPLAY_ORDER, BIKO, ", "DELETE_FLG, INSERT_DT, ",
			"INSERT_CD, UPDATE_DT, ", "UPDATE_CD)", "values (#{genreLgCd,jdbcType=CHAR}, #{genreLgNm,jdbcType=VARCHAR}, ",
			"#{displayOrder,jdbcType=DECIMAL}, #{biko,jdbcType=VARCHAR}, ",
			"#{deleteFlg,jdbcType=CHAR}, #{insertDt,jdbcType=TIMESTAMP}, ",
			"#{insertCd,jdbcType=DECIMAL}, #{updateDt,jdbcType=TIMESTAMP}, ", "#{updateCd,jdbcType=DECIMAL})" })
	int insert(GenreLgEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_LG
	 * @mbg.generated
	 */
	int insertSelective(GenreLgEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_LG
	 * @mbg.generated
	 */
	List<GenreLgEntity> selectByExampleWithRowbounds(GenreLgCriteria example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_LG
	 * @mbg.generated
	 */
	List<GenreLgEntity> selectByExample(GenreLgCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_LG
	 * @mbg.generated
	 */
	@Select({ "select",
			"LG.GENRE_LG_CD as LG_GENRE_LG_CD, LG.GENRE_LG_NM as LG_GENRE_LG_NM, LG.DISPLAY_ORDER as LG_DISPLAY_ORDER, ",
			"LG.BIKO as LG_BIKO, LG.DELETE_FLG as LG_DELETE_FLG, LG.INSERT_DT as LG_INSERT_DT, ",
			"LG.INSERT_CD as LG_INSERT_CD, LG.UPDATE_DT as LG_UPDATE_DT, LG.UPDATE_CD as LG_UPDATE_CD", "from GENRE_LG LG",
			"where LG.GENRE_LG_CD = #{genreLgCd,jdbcType=CHAR}" })
	@ResultMap("com.example.sample.domain.mapper.maintenance.GenreLgMapper.BaseResultMap")
	GenreLgEntity selectByPrimaryKey(String genreLgCd);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_LG
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") GenreLgEntity record, @Param("example") GenreLgCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_LG
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") GenreLgEntity record, @Param("example") GenreLgCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_LG
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(GenreLgEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_LG
	 * @mbg.generated
	 */
	@Update({ "update GENRE_LG", "set GENRE_LG_NM = #{genreLgNm,jdbcType=VARCHAR},",
			"DISPLAY_ORDER = #{displayOrder,jdbcType=DECIMAL},", "BIKO = #{biko,jdbcType=VARCHAR},",
			"DELETE_FLG = #{deleteFlg,jdbcType=CHAR},", "INSERT_DT = #{insertDt,jdbcType=TIMESTAMP},",
			"INSERT_CD = #{insertCd,jdbcType=DECIMAL},", "UPDATE_DT = #{updateDt,jdbcType=TIMESTAMP},",
			"UPDATE_CD = #{updateCd,jdbcType=DECIMAL}", "where GENRE_LG_CD = #{genreLgCd,jdbcType=CHAR}" })
	int updateByPrimaryKey(GenreLgEntity record);

}