package com.example.sample.domain.mapper.maintenance;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

import com.example.sample.domain.entity.maintenance.GenreLgCriteria;
import com.example.sample.domain.entity.maintenance.GenreLgEntity;

/**
 * クラスの説明：大ジャンルマスタ　Mapper
 * @author kamagata
 * @since 2018/02/11
 */
@Mapper
@Repository
public interface GenreLgMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_LG
	 * @mbg.generated
	 */
	long countByExample(GenreLgCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_LG
	 * @mbg.generated
	 */
	int deleteByExample(GenreLgCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_LG
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String genreLgCd);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_LG
	 * @mbg.generated
	 */
	int insert(GenreLgEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_LG
	 * @mbg.generated
	 */
	int insertSelective(GenreLgEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_LG
	 * @mbg.generated
	 */
	List<GenreLgEntity> selectByExampleWithRowbounds(GenreLgCriteria example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_LG
	 * @mbg.generated
	 */
	List<GenreLgEntity> selectByExample(GenreLgCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_LG
	 * @mbg.generated
	 */
	GenreLgEntity selectByPrimaryKey(String genreLgCd);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_LG
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") GenreLgEntity record, @Param("example") GenreLgCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_LG
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") GenreLgEntity record, @Param("example") GenreLgCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_LG
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(GenreLgEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_LG
	 * @mbg.generated
	 */
	int updateByPrimaryKey(GenreLgEntity record);

}