package com.example.sample.domain.mapper.maintenance;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.example.sample.domain.model.maintenance.GenreMd;
import com.example.sample.domain.model.maintenance.GenreMdExample;

@Mapper
public interface GenreMdMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_MD
	 * @mbg.generated
	 */
	long countByExample(GenreMdExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_MD
	 * @mbg.generated
	 */
	int deleteByExample(GenreMdExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_MD
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String genreMdCd);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_MD
	 * @mbg.generated
	 */
	int insert(GenreMd record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_MD
	 * @mbg.generated
	 */
	int insertSelective(GenreMd record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_MD
	 * @mbg.generated
	 */
	List<GenreMd> selectByExample(GenreMdExample example);

	List<GenreMd> selectGenreLgAndMdByExample(GenreMdExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_MD
	 * @mbg.generated
	 */
	GenreMd selectByPrimaryKey(String genreMdCd);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_MD
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") GenreMd record, @Param("example") GenreMdExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_MD
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") GenreMd record, @Param("example") GenreMdExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_MD
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(GenreMd record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_MD
	 * @mbg.generated
	 */
	int updateByPrimaryKey(GenreMd record);
}