package com.example.sample.domain.entity.maintenance;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

/**
 * クラスの説明：
 * @author kamagata
 * @since 2018/02/11
 */
@Component
@Scope("prototype")
public class GenreMdCriteria {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table GENRE_MD
	 * @mbg.generated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table GENRE_MD
	 * @mbg.generated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table GENRE_MD
	 * @mbg.generated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_MD
	 * @mbg.generated
	 */
	public GenreMdCriteria() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_MD
	 * @mbg.generated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_MD
	 * @mbg.generated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_MD
	 * @mbg.generated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_MD
	 * @mbg.generated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_MD
	 * @mbg.generated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_MD
	 * @mbg.generated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_MD
	 * @mbg.generated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_MD
	 * @mbg.generated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_MD
	 * @mbg.generated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GENRE_MD
	 * @mbg.generated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table GENRE_MD
	 * @mbg.generated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andGenreMdCdIsNull() {
			addCriterion("MD.GENRE_MD_CD is null");
			return (Criteria) this;
		}

		public Criteria andGenreMdCdIsNotNull() {
			addCriterion("MD.GENRE_MD_CD is not null");
			return (Criteria) this;
		}

		public Criteria andGenreMdCdEqualTo(String value) {
			addCriterion("MD.GENRE_MD_CD =", value, "genreMdCd");
			return (Criteria) this;
		}

		public Criteria andGenreMdCdNotEqualTo(String value) {
			addCriterion("MD.GENRE_MD_CD <>", value, "genreMdCd");
			return (Criteria) this;
		}

		public Criteria andGenreMdCdGreaterThan(String value) {
			addCriterion("MD.GENRE_MD_CD >", value, "genreMdCd");
			return (Criteria) this;
		}

		public Criteria andGenreMdCdGreaterThanOrEqualTo(String value) {
			addCriterion("MD.GENRE_MD_CD >=", value, "genreMdCd");
			return (Criteria) this;
		}

		public Criteria andGenreMdCdLessThan(String value) {
			addCriterion("MD.GENRE_MD_CD <", value, "genreMdCd");
			return (Criteria) this;
		}

		public Criteria andGenreMdCdLessThanOrEqualTo(String value) {
			addCriterion("MD.GENRE_MD_CD <=", value, "genreMdCd");
			return (Criteria) this;
		}

		public Criteria andGenreMdCdLike(String value) {
			addCriterion("MD.GENRE_MD_CD like", value, "genreMdCd");
			return (Criteria) this;
		}

		public Criteria andGenreMdCdNotLike(String value) {
			addCriterion("MD.GENRE_MD_CD not like", value, "genreMdCd");
			return (Criteria) this;
		}

		public Criteria andGenreMdCdIn(List<String> values) {
			addCriterion("MD.GENRE_MD_CD in", values, "genreMdCd");
			return (Criteria) this;
		}

		public Criteria andGenreMdCdNotIn(List<String> values) {
			addCriterion("MD.GENRE_MD_CD not in", values, "genreMdCd");
			return (Criteria) this;
		}

		public Criteria andGenreMdCdBetween(String value1, String value2) {
			addCriterion("MD.GENRE_MD_CD between", value1, value2, "genreMdCd");
			return (Criteria) this;
		}

		public Criteria andGenreMdCdNotBetween(String value1, String value2) {
			addCriterion("MD.GENRE_MD_CD not between", value1, value2, "genreMdCd");
			return (Criteria) this;
		}

		public Criteria andGenreMdNmIsNull() {
			addCriterion("MD.GENRE_MD_NM is null");
			return (Criteria) this;
		}

		public Criteria andGenreMdNmIsNotNull() {
			addCriterion("MD.GENRE_MD_NM is not null");
			return (Criteria) this;
		}

		public Criteria andGenreMdNmEqualTo(String value) {
			addCriterion("MD.GENRE_MD_NM =", value, "genreMdNm");
			return (Criteria) this;
		}

		public Criteria andGenreMdNmNotEqualTo(String value) {
			addCriterion("MD.GENRE_MD_NM <>", value, "genreMdNm");
			return (Criteria) this;
		}

		public Criteria andGenreMdNmGreaterThan(String value) {
			addCriterion("MD.GENRE_MD_NM >", value, "genreMdNm");
			return (Criteria) this;
		}

		public Criteria andGenreMdNmGreaterThanOrEqualTo(String value) {
			addCriterion("MD.GENRE_MD_NM >=", value, "genreMdNm");
			return (Criteria) this;
		}

		public Criteria andGenreMdNmLessThan(String value) {
			addCriterion("MD.GENRE_MD_NM <", value, "genreMdNm");
			return (Criteria) this;
		}

		public Criteria andGenreMdNmLessThanOrEqualTo(String value) {
			addCriterion("MD.GENRE_MD_NM <=", value, "genreMdNm");
			return (Criteria) this;
		}

		public Criteria andGenreMdNmLike(String value) {
			addCriterion("MD.GENRE_MD_NM like", value, "genreMdNm");
			return (Criteria) this;
		}

		public Criteria andGenreMdNmNotLike(String value) {
			addCriterion("MD.GENRE_MD_NM not like", value, "genreMdNm");
			return (Criteria) this;
		}

		public Criteria andGenreMdNmIn(List<String> values) {
			addCriterion("MD.GENRE_MD_NM in", values, "genreMdNm");
			return (Criteria) this;
		}

		public Criteria andGenreMdNmNotIn(List<String> values) {
			addCriterion("MD.GENRE_MD_NM not in", values, "genreMdNm");
			return (Criteria) this;
		}

		public Criteria andGenreMdNmBetween(String value1, String value2) {
			addCriterion("MD.GENRE_MD_NM between", value1, value2, "genreMdNm");
			return (Criteria) this;
		}

		public Criteria andGenreMdNmNotBetween(String value1, String value2) {
			addCriterion("MD.GENRE_MD_NM not between", value1, value2, "genreMdNm");
			return (Criteria) this;
		}

		public Criteria andDisplayOrderIsNull() {
			addCriterion("MD.DISPLAY_ORDER is null");
			return (Criteria) this;
		}

		public Criteria andDisplayOrderIsNotNull() {
			addCriterion("MD.DISPLAY_ORDER is not null");
			return (Criteria) this;
		}

		public Criteria andDisplayOrderEqualTo(Integer value) {
			addCriterion("MD.DISPLAY_ORDER =", value, "displayOrder");
			return (Criteria) this;
		}

		public Criteria andDisplayOrderNotEqualTo(Integer value) {
			addCriterion("MD.DISPLAY_ORDER <>", value, "displayOrder");
			return (Criteria) this;
		}

		public Criteria andDisplayOrderGreaterThan(Integer value) {
			addCriterion("MD.DISPLAY_ORDER >", value, "displayOrder");
			return (Criteria) this;
		}

		public Criteria andDisplayOrderGreaterThanOrEqualTo(Integer value) {
			addCriterion("MD.DISPLAY_ORDER >=", value, "displayOrder");
			return (Criteria) this;
		}

		public Criteria andDisplayOrderLessThan(Integer value) {
			addCriterion("MD.DISPLAY_ORDER <", value, "displayOrder");
			return (Criteria) this;
		}

		public Criteria andDisplayOrderLessThanOrEqualTo(Integer value) {
			addCriterion("MD.DISPLAY_ORDER <=", value, "displayOrder");
			return (Criteria) this;
		}

		public Criteria andDisplayOrderIn(List<Integer> values) {
			addCriterion("MD.DISPLAY_ORDER in", values, "displayOrder");
			return (Criteria) this;
		}

		public Criteria andDisplayOrderNotIn(List<Integer> values) {
			addCriterion("MD.DISPLAY_ORDER not in", values, "displayOrder");
			return (Criteria) this;
		}

		public Criteria andDisplayOrderBetween(Integer value1, Integer value2) {
			addCriterion("MD.DISPLAY_ORDER between", value1, value2, "displayOrder");
			return (Criteria) this;
		}

		public Criteria andDisplayOrderNotBetween(Integer value1, Integer value2) {
			addCriterion("MD.DISPLAY_ORDER not between", value1, value2, "displayOrder");
			return (Criteria) this;
		}

		public Criteria andGenreLgCdIsNull() {
			addCriterion("MD.GENRE_LG_CD is null");
			return (Criteria) this;
		}

		public Criteria andGenreLgCdIsNotNull() {
			addCriterion("MD.GENRE_LG_CD is not null");
			return (Criteria) this;
		}

		public Criteria andGenreLgCdEqualTo(String value) {
			addCriterion("MD.GENRE_LG_CD =", value, "genreLgCd");
			return (Criteria) this;
		}

		public Criteria andGenreLgCdNotEqualTo(String value) {
			addCriterion("MD.GENRE_LG_CD <>", value, "genreLgCd");
			return (Criteria) this;
		}

		public Criteria andGenreLgCdGreaterThan(String value) {
			addCriterion("MD.GENRE_LG_CD >", value, "genreLgCd");
			return (Criteria) this;
		}

		public Criteria andGenreLgCdGreaterThanOrEqualTo(String value) {
			addCriterion("MD.GENRE_LG_CD >=", value, "genreLgCd");
			return (Criteria) this;
		}

		public Criteria andGenreLgCdLessThan(String value) {
			addCriterion("MD.GENRE_LG_CD <", value, "genreLgCd");
			return (Criteria) this;
		}

		public Criteria andGenreLgCdLessThanOrEqualTo(String value) {
			addCriterion("MD.GENRE_LG_CD <=", value, "genreLgCd");
			return (Criteria) this;
		}

		public Criteria andGenreLgCdLike(String value) {
			addCriterion("MD.GENRE_LG_CD like", value, "genreLgCd");
			return (Criteria) this;
		}

		public Criteria andGenreLgCdNotLike(String value) {
			addCriterion("MD.GENRE_LG_CD not like", value, "genreLgCd");
			return (Criteria) this;
		}

		public Criteria andGenreLgCdIn(List<String> values) {
			addCriterion("MD.GENRE_LG_CD in", values, "genreLgCd");
			return (Criteria) this;
		}

		public Criteria andGenreLgCdNotIn(List<String> values) {
			addCriterion("MD.GENRE_LG_CD not in", values, "genreLgCd");
			return (Criteria) this;
		}

		public Criteria andGenreLgCdBetween(String value1, String value2) {
			addCriterion("MD.GENRE_LG_CD between", value1, value2, "genreLgCd");
			return (Criteria) this;
		}

		public Criteria andGenreLgCdNotBetween(String value1, String value2) {
			addCriterion("MD.GENRE_LG_CD not between", value1, value2, "genreLgCd");
			return (Criteria) this;
		}

		public Criteria andBikoIsNull() {
			addCriterion("MD.BIKO is null");
			return (Criteria) this;
		}

		public Criteria andBikoIsNotNull() {
			addCriterion("MD.BIKO is not null");
			return (Criteria) this;
		}

		public Criteria andBikoEqualTo(String value) {
			addCriterion("MD.BIKO =", value, "biko");
			return (Criteria) this;
		}

		public Criteria andBikoNotEqualTo(String value) {
			addCriterion("MD.BIKO <>", value, "biko");
			return (Criteria) this;
		}

		public Criteria andBikoGreaterThan(String value) {
			addCriterion("MD.BIKO >", value, "biko");
			return (Criteria) this;
		}

		public Criteria andBikoGreaterThanOrEqualTo(String value) {
			addCriterion("MD.BIKO >=", value, "biko");
			return (Criteria) this;
		}

		public Criteria andBikoLessThan(String value) {
			addCriterion("MD.BIKO <", value, "biko");
			return (Criteria) this;
		}

		public Criteria andBikoLessThanOrEqualTo(String value) {
			addCriterion("MD.BIKO <=", value, "biko");
			return (Criteria) this;
		}

		public Criteria andBikoLike(String value) {
			addCriterion("MD.BIKO like", value, "biko");
			return (Criteria) this;
		}

		public Criteria andBikoNotLike(String value) {
			addCriterion("MD.BIKO not like", value, "biko");
			return (Criteria) this;
		}

		public Criteria andBikoIn(List<String> values) {
			addCriterion("MD.BIKO in", values, "biko");
			return (Criteria) this;
		}

		public Criteria andBikoNotIn(List<String> values) {
			addCriterion("MD.BIKO not in", values, "biko");
			return (Criteria) this;
		}

		public Criteria andBikoBetween(String value1, String value2) {
			addCriterion("MD.BIKO between", value1, value2, "biko");
			return (Criteria) this;
		}

		public Criteria andBikoNotBetween(String value1, String value2) {
			addCriterion("MD.BIKO not between", value1, value2, "biko");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgIsNull() {
			addCriterion("MD.DELETE_FLG is null");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgIsNotNull() {
			addCriterion("MD.DELETE_FLG is not null");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgEqualTo(String value) {
			addCriterion("MD.DELETE_FLG =", value, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgNotEqualTo(String value) {
			addCriterion("MD.DELETE_FLG <>", value, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgGreaterThan(String value) {
			addCriterion("MD.DELETE_FLG >", value, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgGreaterThanOrEqualTo(String value) {
			addCriterion("MD.DELETE_FLG >=", value, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgLessThan(String value) {
			addCriterion("MD.DELETE_FLG <", value, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgLessThanOrEqualTo(String value) {
			addCriterion("MD.DELETE_FLG <=", value, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgLike(String value) {
			addCriterion("MD.DELETE_FLG like", value, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgNotLike(String value) {
			addCriterion("MD.DELETE_FLG not like", value, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgIn(List<String> values) {
			addCriterion("MD.DELETE_FLG in", values, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgNotIn(List<String> values) {
			addCriterion("MD.DELETE_FLG not in", values, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgBetween(String value1, String value2) {
			addCriterion("MD.DELETE_FLG between", value1, value2, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgNotBetween(String value1, String value2) {
			addCriterion("MD.DELETE_FLG not between", value1, value2, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andInsertCdIsNull() {
			addCriterion("MD.INSERT_CD is null");
			return (Criteria) this;
		}

		public Criteria andInsertCdIsNotNull() {
			addCriterion("MD.INSERT_CD is not null");
			return (Criteria) this;
		}

		public Criteria andInsertCdEqualTo(Long value) {
			addCriterion("MD.INSERT_CD =", value, "insertCd");
			return (Criteria) this;
		}

		public Criteria andInsertCdNotEqualTo(Long value) {
			addCriterion("MD.INSERT_CD <>", value, "insertCd");
			return (Criteria) this;
		}

		public Criteria andInsertCdGreaterThan(Long value) {
			addCriterion("MD.INSERT_CD >", value, "insertCd");
			return (Criteria) this;
		}

		public Criteria andInsertCdGreaterThanOrEqualTo(Long value) {
			addCriterion("MD.INSERT_CD >=", value, "insertCd");
			return (Criteria) this;
		}

		public Criteria andInsertCdLessThan(Long value) {
			addCriterion("MD.INSERT_CD <", value, "insertCd");
			return (Criteria) this;
		}

		public Criteria andInsertCdLessThanOrEqualTo(Long value) {
			addCriterion("MD.INSERT_CD <=", value, "insertCd");
			return (Criteria) this;
		}

		public Criteria andInsertCdIn(List<Long> values) {
			addCriterion("MD.INSERT_CD in", values, "insertCd");
			return (Criteria) this;
		}

		public Criteria andInsertCdNotIn(List<Long> values) {
			addCriterion("MD.INSERT_CD not in", values, "insertCd");
			return (Criteria) this;
		}

		public Criteria andInsertCdBetween(Long value1, Long value2) {
			addCriterion("MD.INSERT_CD between", value1, value2, "insertCd");
			return (Criteria) this;
		}

		public Criteria andInsertCdNotBetween(Long value1, Long value2) {
			addCriterion("MD.INSERT_CD not between", value1, value2, "insertCd");
			return (Criteria) this;
		}

		public Criteria andInsertDtIsNull() {
			addCriterion("MD.INSERT_DT is null");
			return (Criteria) this;
		}

		public Criteria andInsertDtIsNotNull() {
			addCriterion("MD.INSERT_DT is not null");
			return (Criteria) this;
		}

		public Criteria andInsertDtEqualTo(Date value) {
			addCriterion("MD.INSERT_DT =", value, "insertDt");
			return (Criteria) this;
		}

		public Criteria andInsertDtNotEqualTo(Date value) {
			addCriterion("MD.INSERT_DT <>", value, "insertDt");
			return (Criteria) this;
		}

		public Criteria andInsertDtGreaterThan(Date value) {
			addCriterion("MD.INSERT_DT >", value, "insertDt");
			return (Criteria) this;
		}

		public Criteria andInsertDtGreaterThanOrEqualTo(Date value) {
			addCriterion("MD.INSERT_DT >=", value, "insertDt");
			return (Criteria) this;
		}

		public Criteria andInsertDtLessThan(Date value) {
			addCriterion("MD.INSERT_DT <", value, "insertDt");
			return (Criteria) this;
		}

		public Criteria andInsertDtLessThanOrEqualTo(Date value) {
			addCriterion("MD.INSERT_DT <=", value, "insertDt");
			return (Criteria) this;
		}

		public Criteria andInsertDtIn(List<Date> values) {
			addCriterion("MD.INSERT_DT in", values, "insertDt");
			return (Criteria) this;
		}

		public Criteria andInsertDtNotIn(List<Date> values) {
			addCriterion("MD.INSERT_DT not in", values, "insertDt");
			return (Criteria) this;
		}

		public Criteria andInsertDtBetween(Date value1, Date value2) {
			addCriterion("MD.INSERT_DT between", value1, value2, "insertDt");
			return (Criteria) this;
		}

		public Criteria andInsertDtNotBetween(Date value1, Date value2) {
			addCriterion("MD.INSERT_DT not between", value1, value2, "insertDt");
			return (Criteria) this;
		}

		public Criteria andUpdateCdIsNull() {
			addCriterion("MD.UPDATE_CD is null");
			return (Criteria) this;
		}

		public Criteria andUpdateCdIsNotNull() {
			addCriterion("MD.UPDATE_CD is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateCdEqualTo(Long value) {
			addCriterion("MD.UPDATE_CD =", value, "updateCd");
			return (Criteria) this;
		}

		public Criteria andUpdateCdNotEqualTo(Long value) {
			addCriterion("MD.UPDATE_CD <>", value, "updateCd");
			return (Criteria) this;
		}

		public Criteria andUpdateCdGreaterThan(Long value) {
			addCriterion("MD.UPDATE_CD >", value, "updateCd");
			return (Criteria) this;
		}

		public Criteria andUpdateCdGreaterThanOrEqualTo(Long value) {
			addCriterion("MD.UPDATE_CD >=", value, "updateCd");
			return (Criteria) this;
		}

		public Criteria andUpdateCdLessThan(Long value) {
			addCriterion("MD.UPDATE_CD <", value, "updateCd");
			return (Criteria) this;
		}

		public Criteria andUpdateCdLessThanOrEqualTo(Long value) {
			addCriterion("MD.UPDATE_CD <=", value, "updateCd");
			return (Criteria) this;
		}

		public Criteria andUpdateCdIn(List<Long> values) {
			addCriterion("MD.UPDATE_CD in", values, "updateCd");
			return (Criteria) this;
		}

		public Criteria andUpdateCdNotIn(List<Long> values) {
			addCriterion("MD.UPDATE_CD not in", values, "updateCd");
			return (Criteria) this;
		}

		public Criteria andUpdateCdBetween(Long value1, Long value2) {
			addCriterion("MD.UPDATE_CD between", value1, value2, "updateCd");
			return (Criteria) this;
		}

		public Criteria andUpdateCdNotBetween(Long value1, Long value2) {
			addCriterion("MD.UPDATE_CD not between", value1, value2, "updateCd");
			return (Criteria) this;
		}

		public Criteria andUpdateDtIsNull() {
			addCriterion("MD.UPDATE_DT is null");
			return (Criteria) this;
		}

		public Criteria andUpdateDtIsNotNull() {
			addCriterion("MD.UPDATE_DT is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateDtEqualTo(Date value) {
			addCriterion("MD.UPDATE_DT =", value, "updateDt");
			return (Criteria) this;
		}

		public Criteria andUpdateDtNotEqualTo(Date value) {
			addCriterion("MD.UPDATE_DT <>", value, "updateDt");
			return (Criteria) this;
		}

		public Criteria andUpdateDtGreaterThan(Date value) {
			addCriterion("MD.UPDATE_DT >", value, "updateDt");
			return (Criteria) this;
		}

		public Criteria andUpdateDtGreaterThanOrEqualTo(Date value) {
			addCriterion("MD.UPDATE_DT >=", value, "updateDt");
			return (Criteria) this;
		}

		public Criteria andUpdateDtLessThan(Date value) {
			addCriterion("MD.UPDATE_DT <", value, "updateDt");
			return (Criteria) this;
		}

		public Criteria andUpdateDtLessThanOrEqualTo(Date value) {
			addCriterion("MD.UPDATE_DT <=", value, "updateDt");
			return (Criteria) this;
		}

		public Criteria andUpdateDtIn(List<Date> values) {
			addCriterion("MD.UPDATE_DT in", values, "updateDt");
			return (Criteria) this;
		}

		public Criteria andUpdateDtNotIn(List<Date> values) {
			addCriterion("MD.UPDATE_DT not in", values, "updateDt");
			return (Criteria) this;
		}

		public Criteria andUpdateDtBetween(Date value1, Date value2) {
			addCriterion("MD.UPDATE_DT between", value1, value2, "updateDt");
			return (Criteria) this;
		}

		public Criteria andUpdateDtNotBetween(Date value1, Date value2) {
			addCriterion("MD.UPDATE_DT not between", value1, value2, "updateDt");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table GENRE_MD
	 * @mbg.generated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
	 * This class was generated by MyBatis Generator.
	 * This class corresponds to the database table GENRE_MD
	 *
	 * @mbg.generated do_not_delete_during_merge
	 */
	public static class Criteria extends GeneratedCriteria {

		protected Criteria() {
			super();
		}

		public Criteria andGenreLgNmLike(String value) {
			addCriterion("LG.GENRE_LG_NM like", value, "genreLgNm");
			return this;
		}
	}
}