package com.example.sample.domain.entity.maintenance;

import java.io.Serializable;

import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import com.example.sample.domain.entity.common.CommonColumnEntity;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

/**
 * クラスの説明：大ジャンルエンティティ
 * @author kamagata
 * @since 2018/02/15
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table GENRE_LG
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = false)
@Component
@Scope("prototype")
public class GenreLgEntity extends CommonColumnEntity implements Serializable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GENRE_LG.GENRE_LG_CD
	 * @mbg.generated
	 */
	private String genreLgCd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GENRE_LG.GENRE_LG_NM
	 * @mbg.generated
	 */
	private String genreLgNm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GENRE_LG.DISPLAY_ORDER
	 * @mbg.generated
	 */
	private Integer displayOrder;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table GENRE_LG
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

}